Add buildEnvironment method to propagate information from SCM to builds
jenkinsci/repo-plugin pull request #74
Opened 2021-07-02 13:03 UTC by abioteau

Add REPO_MANIFEST environment variable to get static manifest from pipeline scm step

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-07-05 06:21 UTC, abioteau commented
@francoisferrand can you please review this PR ?

2021-07-11 18:05 UTC, francoisferrand requested changes
While I like the idea, I think we should expose more variables to make it useful in most cases : e.g. also repo manifest url, filename, ...

I wonder however how it will behave if the step is used multiple times in the same build. Will the env be simply override on next call (without affecting parallel calls) ?

e.g. in this case:

```
repo 'url0'
echo env.REPO_MANIFEST // --> from url0
parallel part1: {
   repo 'url1'
   echo env.REPO_MANIFEST // --> from url1
}, part2: {
   repo 'url2'
   echo env.REPO_MANIFEST // --> from url2
}
repo 'url3'
echo env.REPO_MANIFEST // --> from url3
```

2021-08-13 14:19 UTC, abioteau commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +				env.put("REPO_MANIFEST", state.getManifest());
Ok. I propose to rename it into REPO_MANIFEST_XML.

2021-08-13 15:25 UTC, abioteau commented
> While I like the idea, I think we should expose more variables to make it useful in most cases : e.g. also repo manifest url, filename, ...
> 
> I wonder however how it will behave if the step is used multiple times in the same build. Will the env be simply override on next call (without affecting parallel calls) ?
> 
> e.g. in this case:
> 
> ```
> repo 'url0'
> echo env.REPO_MANIFEST // --> from url0
> parallel part1: {
>    repo 'url1'
>    echo env.REPO_MANIFEST // --> from url1
> }, part2: {
>    repo 'url2'
>    echo env.REPO_MANIFEST // --> from url2
> }
> repo 'url3'
> echo env.REPO_MANIFEST // --> from url3
> ```

In fact, `buildEnvironment()` method is used by SCM workflow at the end of checkout operation to return a map of SCM contributed variables (https://github.com/jenkinsci/workflow-scm-step-plugin/blob/40970db36f37545b0364a5a7aa067a57f4b9297f/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/SCMStep.java#L98-L99), if i understood correctly. :smiley:

If the step is used multiple times in the same build, you would get a map for each step.

e.g. in this case:
```
env0 = checkout(repo 'url0')
echo env0.REPO_MANIFEST_XML // --> from url0
parallel part1: {
   env0 = checkout(repo 'url1')
   echo env1.REPO_MANIFEST_XML // --> from url1
}, part2: {
   env2 = checkout(repo 'url2')
   echo env2.REPO_MANIFEST_XML // --> from url2
}
env3 = checkout(repo 'url3')
echo env3.REPO_MANIFEST_XML // --> from url3
```

2021-11-08 09:00 UTC, francoisferrand requested changes

2021-11-08 10:43 UTC, abioteau commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +		for (RevisionState state : stateList) {
I cannot use `getLastState()` as is because I do not want to search revision state on previous build but I can propose something to avoid duplication. ;-)

2021-11-08 14:41 UTC, abioteau commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +		for (RevisionState state : stateList) {
Have a look on https://github.com/jenkinsci/repo-plugin/pull/74/commits/1a115ca70118238e2f42bbf3500239a36d3c0867

2021-11-09 08:43 UTC, francoisferrand commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +			env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
should also return other variables : like REPO_MANIFEST_URL, REPO_MANIFEST_BRANCH, REPO_MANIFEST_FILE ?

2021-11-09 08:47 UTC, francoisferrand commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +			env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
Also, we should try to find a place to document these exported variables (available through the jenkins ui) : so that they can be used without having to dig through the code.... i.e. somewhere in `src/main/webapp` i guess

2021-11-16 14:01 UTC, abioteau commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +			env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
Hi @francoisferrand, 

The other variables (manifest url, branch and filename) are already passed in the pipeline as argument to the `checkout()` operation. So I could add it but it is unnecessary.

For the documentation, this is not a new option, as `worktree` for example, so I can not add it on `src/main/webapp`.

2021-11-24 08:50 UTC, francoisferrand commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +			env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
The other variables are passed in pipeline argument, but default argument may be passed, and returning the values allows to simplify code, by allowing the to have code which only depends on the result of the checkout instead of having to wrap all code (and thus deal with new parameters all the time). This is certainly not used all the time, but happens regularly, and worth the time to add it now.

The documentation can be added to the `src/main/resources/hudson/plugins/repo/RepoScm/help.html` file, like what is done for Git : https://github.com/jenkinsci/git-plugin/blob/master/src/main/resources/hudson/plugins/git/GitSCM/help.html

2021-12-21 16:37 UTC, abioteau commented on src/main/java/hudson/plugins/repo/RepoScm.java
> +			env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
Hi @francoisferrand, I added other variables and updated documentation.

2021-12-22 20:13 UTC, francoisferrand approved these changes

2021-12-22 20:13 UTC, francoisferrand commented
LGTM, thanks !

2021-12-22 20:13 UTC, merged

2022-03-09 08:08 UTC, daniel-beck commented
Broke https://plugins.jenkins.io/repo/ because https://github.com/jenkinsci/repo-plugin/blob/729f5c57bf4cd8fe31f6502c90854ba0f24de464/pom.xml#L16

2022-07-03 04:40 UTC, maksonlee commented
```
if (state != SCMRevisionState.NONE) {
   env.put("REPO_MANIFEST_URL", ((RevisionState) state).getUrl());
   env.put("REPO_MANIFEST_BRANCH", ((RevisionState) state).getBranch());
   env.put("REPO_MANIFEST_FILE", ((RevisionState) state).getFile());
   env.put("REPO_MANIFEST_XML", ((RevisionState) state).getManifest());
}
```

At some situation, REPO_MANIFEST_XML is a big file and get to expand and then add to env will cause following exception,
```
java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to user-scm
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1124)
		at hudson.Launcher$ProcStarter.start(Launcher.java:509)
		at hudson.Launcher$ProcStarter.join(Launcher.java:520)
		at hudson.plugins.repo.RepoScm.checkoutCode(RepoScm.java:1108)
		at hudson.plugins.repo.RepoScm.checkout(RepoScm.java:917)
		at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:143)
		at hudson.scm.SCM.checkout(SCM.java:540)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1217)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:647)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:519)
		at hudson.model.Run.execute(Run.java:1897)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
		at hudson.model.ResourceController.execute(ResourceController.java:101)
		at hudson.model.Executor.run(Executor.java:442)
Caused: java.io.IOException: Cannot run program "repo" (in directory "/home/user/workspace/test/amss"): error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:254)
	at hudson.Proc$LocalProc.<init>(Proc.java:223)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:997)
	at hudson.Launcher$ProcStarter.start(Launcher.java:509)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1398)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1340)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```