[JENKINS-64150] Fix blank manifest view
jenkinsci/repo-plugin pull request #76
Opened 2022-01-05 10:13 UTC by abioteau

As describe on https://github.com/jenkinsci/repo-plugin/pull/75 and on [JENKINS-64150](https://issues.jenkins.io/browse/JENKINS-64150), the repo manifest informations are blanked on existing jobs after restart of Jenkins server.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-01-05 14:15 UTC, abioteau commented
Hi @francoisferrand, could you have a look on this PR?

2022-05-30 14:25 UTC, francoisferrand requested changes

2022-05-30 14:25 UTC, francoisferrand commented on src/main/java/hudson/plugins/repo/ManifestAction.java
> +	private RevisionState revisionState;
`revisionState` is a large object, which should not be persisted I think : it will anyway be re-loaded on call to setIndex.
Isn't the `@DataBoundSetter` annotation enough to fix the problem here?

2022-09-13 07:33 UTC, abioteau commented
Issue solved by https://github.com/jenkinsci/repo-plugin/pull/82

2022-09-13 07:33 UTC, closed without merging